run:
	python3 Python.py

	javac Java.java
	java Java
	

	gcc C.c -o C
	./C

	cd Rust && cargo run

	racket Scheme.rkt

	erlc perlang.erl
	erl -noshell -s perlang main

	rm -f Java.class perlang.beam C

