run:
	@echo "---- Ejecutando ejercicio1 ----"
	python3 ejercicio1.py

	@echo "---- Ejecutando ejercicio2 ----"
	python3 ejercicio2.py

	@echo "---- Ejecutando ejercicio3 ----"
	python3 ejercicio3.py

	@echo "---- Ejecutando ejercicio4 ----"
	python3 ejercicio4.py