run:
	@echo "---- Ejecutando ejercicio1 ----"
	python3 ejercicio1.py

	@echo "\n---- Ejecutando ejercicio2 ----"
	python3 ejercicio2.py

	@echo "\n---- Ejecutando ejercicio3 ----"
	python3 ejercicio3.py

	@echo "\n---- Ejecutando ejercicio4 ----"
	python3 ejercicio4.py

	@echo "\n---- Ejecutando ejercicio5 ----"
	python3 ejercicio5.py

	@echo "\n---- Ejecutando ejercicio6 ----"
	python3 ejercicio6.py

	@echo "\n---- Ejecutando ejercicio7 ----"
	python3 ejercicio7.py

	@echo "\n---- Ejecutando ejercicio8 ----"
	python3 ejercicio8.py

	@echo "\n---- Ejecutando ejercicio9 ----"
	python3 ejercicio9.py

	@echo "\n---- Ejecutando ejercicio10 ----"
	python3 ejercicio10.py